name: exel-processor
services:
  frontend:
    image: dariobastosdev/exel-processor:front1.0.0
    container_name: front
    ports:
      - '80:80'
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - exel-processor

  backend:
    image: dariobastosdev/exel-processor:back1.0.0
    container_name: back
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=file:./sheet.db
    volumes:
      - sqlite_data:/usr/src/app/prisma/
      - ./uploads:/usr/src/app/uploads
    networks:
      - exel-processor
    restart: unless-stopped

networks:
  exel-processor:
    driver: bridge

volumes:
  sqlite_data:
